
name: Private Payment CI

 on: 
    workflow dispatch:
    push:
        branches: ["main"]
      pull_request:
        branches: ["main"]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Fazer Checkout do repositório
        uses: actions/checkout@v4

      - name: Definir a versão do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install

      - name: Iniciar API
        run: npm start &

      - name: Aguardar a API Iniciar
        run: sleep 15

      - name: Executar os testes
        run: npm test